// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSYr1Wfx8IxjGkyboLfs2Iv7sKg_ETDA',
    appId: '1:854899114966:web:bedfe4c3838885a82a1a77',
    messagingSenderId: '854899114966',
    projectId: 'inventario-app-abe77',
    authDomain: 'inventario-app-abe77.firebaseapp.com',
    storageBucket: 'inventario-app-abe77.firebasestorage.app',
    measurementId: 'G-3L9QY82BF9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTkSUyNIdOPHTGNLOLqX1vMHIzVUmTMqU',
    appId: '1:854899114966:ios:8d1a84c3efe07d992a1a77',
    messagingSenderId: '854899114966',
    projectId: 'inventario-app-abe77',
    storageBucket: 'inventario-app-abe77.firebasestorage.app',
    iosBundleId: 'com.mattphone.inventarioApp',
  );
}
